<?php

namespace App\Services;

use App\Models\CAP_Stuff\CAP;
use App\Models\CAP_Stuff\WriteXML;

/**
 * CAPService
 * 
 * Handles the generation of Common Alerting Protocol (CAP) 1.2 XML messages.
 * This service acts as a bridge between the application's internal data structures
 * and the standardized CAP XML format required for alerts.
 */
class CAPService {

    /**
     * Generates a full CAP XML document for a single disaster event.
     * @param array $data The raw disaster data from the database.
     * @param string $type The type of disaster ('flood', 'fire', 'earthquake').
     * @return string The complete XML document as a string.
     */
    public function generateXml($data, $type) {
        // 1. Create a blank CAP data object.
        $cap = new CAP();
        // 2. Map the raw database data to the structured CAP object.
        $this->mapDataToCap($cap, $data, $type);

        // 3. Create an XML writer and build the document from the CAP object.
        $xml = new WriteXML("1.0", "UTF-8");
        
        // --- Root Element ---
        $xml->tagOpen("cap:alert", [
            'xmlns:cap' => 'urn:oasis:names:tc:emergency:cap:1.2'
        ]);

        // --- Alert Metadata ---
        $xml->tagSimple("cap:identifier", $cap->identifier);
        $xml->tagSimple("cap:sender", $cap->sender);
        $xml->tagSimple("cap:sent", $cap->sent);
        $xml->tagSimple("cap:status", $cap->status);
        $xml->tagSimple("cap:msgType", $cap->msgType);
        $xml->tagSimple("cap:source", $cap->source);
        $xml->tagSimple("cap:scope", $cap->scope);

        // --- Info Block (The main content of the alert) ---
        $xml->tagOpen("cap:info");
        $xml->tagSimple("cap:category", $cap->category[0]);
        $xml->tagSimple("cap:event", $cap->event);
        $xml->tagSimple("cap:urgency", $cap->urgency);
        $xml->tagSimple("cap:severity", $cap->severity);
        $xml->tagSimple("cap:certainty", $cap->certainty);
        $xml->tagSimple("cap:headline", $cap->headline);
        $xml->tagSimple("cap:description", $cap->description);

        // --- Instruction Block ---
        // Dynamically includes information about nearby shelters.
        $shelterModel = new \App\Models\Shelter();
        $shelters = $shelterModel->getAll(5); // Get up to 5 shelters.
        $instructionText = "Please proceed to the nearest safe shelter. Available shelters: ";
        if (!empty($shelters)) {
            $shelterList = [];
            foreach ($shelters as $s) {
                $shelterList[] = "{$s['name']} (Lat: {$s['latitude']}, Lng: {$s['longitude']})";
            }
            $instructionText .= implode(", ", $shelterList);
        } else {
            $instructionText .= "None currently listed in the system.";
        }
        $xml->tagSimple("cap:instruction", $instructionText);

        $xml->tagSimple("cap:web", $cap->web);

        // --- Resource Block ---
        // Provides a link to the original alert source for more information.
        $xml->tagOpen("cap:resource");
        $xml->tagSimple("cap:resourceDesc", "External Link to Original Alert");
        $xml->tagSimple("cap:mimeType", "text/html");
        $xml->tagSimple("cap:uri", $cap->web);
        $xml->tagClose("cap:resource");

        // --- Area Block ---
        // Describes the geographic area affected by the alert.
        $xml->tagOpen("cap:area");
        $xml->tagSimple("cap:areaDesc", $cap->areaDesc);
        // CAP uses "lat,long radius" format for a circle. A radius of 0 indicates a point location.
        $xml->tagSimple("cap:circle", "{$data['latitude']},{$data['longitude']} 0"); 
        $xml->tagClose("cap:area");

        $xml->tagClose("cap:info");
        $xml->tagClose("cap:alert");

        return $xml->output();
    }

    /**
     * Maps the raw data from the database to the structured CAP object.
     * This method centralizes the data mapping logic, keeping it separate from the XML generation logic.
     * @param CAP $cap The CAP object to be filled (passed by reference).
     * @param array $data The raw data array from a model (e.g., from Earthquake::getById).
     * @param string $type The type of disaster ('flood', 'fire', 'earthquake').
     */
    private function mapDataToCap(CAP &$cap, $data, $type) {
        // --- General Info (common to all disaster types) ---
        $cap->identifier = "CoA-{$type}-" . ($data['external_id'] ?? $data['id']);
        $cap->sender     = "crisis-containment-service@coa.ro";
        
        $time = strtotime($data['event_time']);
        $cap->sent = date('Y-m-d\TH:i:sP', $time); 
        
        $cap->status  = "Actual";
        $cap->msgType = "Alert";
        $cap->source  = "CoA System / " . ($data['source'] ?? 'GDACS');
        $cap->scope   = "Public";
        $cap->urgency     = "Immediate";
        $cap->certainty   = "Observed";
        $cap->description = "Automated message generated by the CoA system for natural hazard monitoring.";
        $cap->areaDesc    = $data['region'] ?? ($data['title'] ?? 'Unspecified Location');

        // --- Type-Specific Info ---
        // Sets details that vary by disaster type.
        switch ($type) {
            case 'flood':
                $cap->category = ["Met"]; // Meteorological
                $cap->event    = "Flood Alert";
                $cap->severity = "Severe";
                $cap->headline = "Flood Alert: " . ($data['title'] ?? 'N/A');
                break;
            case 'fire':
                $cap->category = ["Fire"];
                $cap->event    = "Wildfire Alert";
                $cap->severity = "Extreme";
                $cap->headline = "Wildfire Alert: " . ($data['title'] ?? 'N/A');
                break;
            case 'earthquake':
                $cap->category = ["Geo"]; // Geophysical
                $cap->event    = "Earthquake Detection";
                $cap->severity = "Moderate";
                $cap->headline = "Earthquake Detection: Magnitude " . ($data['magnitude'] ?? '?');
                break;
        }

        // --- External Link ---
        // Constructs a direct link to the event page on the original source's website.
        $extId = $data['external_id'] ?? '0';
        switch ($type) {
            case 'flood':
                $cap->web = "https://www.gdacs.org/report.aspx?eventtype=FL&eventid=" . preg_replace('/[^0-9]/', '', $extId);
                break;
            case 'fire':
                $cap->web = "https://www.gdacs.org/report.aspx?eventtype=WF&eventid=" . preg_replace('/[^0-9]/', '', $extId);
                break;
            case 'earthquake':
                $cap->web = "https://www.emsc-csem.org/Earthquake/earthquake.php?id=" . $extId;
                break;
            default:
                $cap->web = "https://www.gdacs.org/";
        }
    }
}
