<?php

namespace App\Services;

use App\Models\CAP_Stuff\CAP;
use App\Models\CAP_Stuff\xml as XMLWriter;

class CAPService {

    public function generateXml($data, $type) {
        $cap = new CAP();
        $this->mapDataToCap($cap, $data, $type);

        $xml = new XMLWriter("1.0", "UTF-8");
        
        $xml->tagOpen("alert", [
            'xmlns:cap' => 'urn:oasis:names:tc:emergency:cap:1.2'
        ]);

        $xml->tagSimple("identifier", $cap->identifier);
        $xml->tagSimple("sender", $cap->sender);
        $xml->tagSimple("sent", $cap->sent);
        $xml->tagSimple("status", $cap->status);
        $xml->tagSimple("msgType", $cap->msgType);
        $xml->tagSimple("source", $cap->source);
        $xml->tagSimple("scope", $cap->scope);

        $xml->tagOpen("info");
        $xml->tagSimple("category", $cap->category[0]);
        $xml->tagSimple("event", $cap->event);
        $xml->tagSimple("urgency", $cap->urgency);
        $xml->tagSimple("severity", $cap->severity);
        $xml->tagSimple("certainty", $cap->certainty);
        $xml->tagSimple("headline", $cap->headline);
        $xml->tagSimple("description", $cap->description);
        $xml->tagSimple("web", $cap->web);

        $xml->tagOpen("resource");
        $xml->tagSimple("resourceDesc", "External Link to Original Alert");
        $xml->tagSimple("mimeType", "text/html");
        $xml->tagSimple("uri", $cap->web);
        $xml->tagClose("resource");

        $xml->tagOpen("area");
        $xml->tagSimple("areaDesc", $cap->areaDesc);
        $xml->tagSimple("circle", "{$data['latitude']},{$data['longitude']} 0"); 
        $xml->tagClose("area");

        $xml->tagClose("info");
        $xml->tagClose("alert");

        return $xml->output();
    }

    private function mapDataToCap(CAP $cap, $data, $type) {
        $cap->identifier = "CoA-{$type}-" . ($data['external_id'] ?? $data['id']);
        $cap->sender     = "crisis-containment-service@coa.ro";
        
        $time = strtotime($data['event_time']);
        $cap->sent = date('Y-m-d\TH:i:sP', $time); 
        
        $cap->status  = "Actual";
        $cap->msgType = "Alert";
        $cap->source  = "CoA System / " . ($data['source'] ?? 'GDACS');
        $cap->scope   = "Public";

        switch ($type) {
            case 'flood':
                $cap->category = ["Met"];
                $cap->event    = "Flood Alert";
                $cap->severity = "Severe";
                $cap->headline = "Flood Alert: " . ($data['title'] ?? 'N/A');
                break;
            case 'fire':
                $cap->category = ["Fire"];
                $cap->event    = "Wildfire Alert";
                $cap->severity = "Extreme";
                $cap->headline = "Wildfire Alert: " . ($data['title'] ?? 'N/A');
                break;
            case 'earthquake':
                $cap->category = ["Geo"];
                $cap->event    = "Earthquake Detection";
                $cap->severity = "Moderate";
                $cap->headline = "Earthquake Detection: Magnitude " . ($data['magnitude'] ?? '?');
                break;
        }

        $cap->urgency     = "Immediate";
        $cap->certainty   = "Observed";
        $cap->description = "Automated message generated by the CoA system for natural hazard monitoring.";
        $cap->areaDesc    = $data['region'] ?? ($data['title'] ?? 'Unspecified Location');

        // Construct source URLs dynamically based on type and external ID
        $extId = $data['external_id'] ?? '0';
        switch ($type) {
            case 'flood':
                $cap->web = "https://www.gdacs.org/report.aspx?eventtype=FL&eventid=" . preg_replace('/[^0-9]/', '', $extId);
                break;
            case 'fire':
                $cap->web = "https://www.gdacs.org/report.aspx?eventtype=WF&eventid=" . preg_replace('/[^0-9]/', '', $extId);
                break;
            case 'earthquake':
                // SeismicPortal/EMSC earthquake detail link
                $cap->web = "https://www.emsc-csem.org/Earthquake/earthquake.php?id=" . $extId;
                break;
            default:
                $cap->web = "https://www.gdacs.org/";
        }
    }
}
