<?php

namespace App\Services;

use App\Models\CAP_Stuff\CAP;
use App\Models\CAP_Stuff\xml as XMLWriter;

/**
 * CAPService
 * 
 * Handles the generation of CAP 1.2 XML messages.
 * Uses the 'cap:' prefix for all elements to ensure compatibility when embedded in RSS feeds.
 */
class CAPService {

    public function generateXml($data, $type) {
        $cap = new CAP();
        $this->mapDataToCap($cap, $data, $type);

        $xml = new XMLWriter("1.0", "UTF-8");
        
        // Root element <cap:alert> with namespace definition
        $xml->tagOpen("cap:alert", [
            'xmlns:cap' => 'urn:oasis:names:tc:emergency:cap:1.2'
        ]);

        $xml->tagSimple("cap:identifier", $cap->identifier);
        $xml->tagSimple("cap:sender", $cap->sender);
        $xml->tagSimple("cap:sent", $cap->sent);
        $xml->tagSimple("cap:status", $cap->status);
        $xml->tagSimple("cap:msgType", $cap->msgType);
        $xml->tagSimple("cap:source", $cap->source);
        $xml->tagSimple("cap:scope", $cap->scope);

        $xml->tagOpen("cap:info");
        $xml->tagSimple("cap:category", $cap->category[0]);
        $xml->tagSimple("cap:event", $cap->event);
        $xml->tagSimple("cap:urgency", $cap->urgency);
        $xml->tagSimple("cap:severity", $cap->severity);
        $xml->tagSimple("cap:certainty", $cap->certainty);
        $xml->tagSimple("cap:headline", $cap->headline);
        $xml->tagSimple("cap:description", $cap->description);

        // Include available shelters in the instructions
        $shelterModel = new \App\Models\Shelter();
        $shelters = $shelterModel->getAll(5); // Get up to 5 shelters
        $instructionText = "Please proceed to the nearest safe shelter. Available shelters: ";
        if (!empty($shelters)) {
            $shelterList = [];
            foreach ($shelters as $s) {
                $shelterList[] = "{$s['name']} (Lat: {$s['latitude']}, Lng: {$s['longitude']})";
            }
            $instructionText .= implode(", ", $shelterList);
        } else {
            $instructionText .= "None currently listed in the system.";
        }
        $xml->tagSimple("cap:instruction", $instructionText);

        $xml->tagSimple("cap:web", $cap->web);

        $xml->tagOpen("cap:resource");
        $xml->tagSimple("cap:resourceDesc", "External Link to Original Alert");
        $xml->tagSimple("cap:mimeType", "text/html");
        $xml->tagSimple("cap:uri", $cap->web);
        $xml->tagClose("cap:resource");

        $xml->tagOpen("cap:area");
        $xml->tagSimple("cap:areaDesc", $cap->areaDesc);
        // CAP uses "lat,long" format for circle
        $xml->tagSimple("cap:circle", "{$data['latitude']},{$data['longitude']} 0"); 
        $xml->tagClose("cap:area");

        $xml->tagClose("cap:info");
        $xml->tagClose("cap:alert");

        return $xml->output();
    }

    private function mapDataToCap(CAP $cap, $data, $type) {
        $cap->identifier = "CoA-{$type}-" . ($data['external_id'] ?? $data['id']);
        $cap->sender     = "crisis-containment-service@coa.ro";
        
        $time = strtotime($data['event_time']);
        $cap->sent = date('Y-m-d\TH:i:sP', $time); 
        
        $cap->status  = "Actual";
        $cap->msgType = "Alert";
        $cap->source  = "CoA System / " . ($data['source'] ?? 'GDACS');
        $cap->scope   = "Public";

        switch ($type) {
            case 'flood':
                $cap->category = ["Met"];
                $cap->event    = "Flood Alert";
                $cap->severity = "Severe";
                $cap->headline = "Flood Alert: " . ($data['title'] ?? 'N/A');
                break;
            case 'fire':
                $cap->category = ["Fire"];
                $cap->event    = "Wildfire Alert";
                $cap->severity = "Extreme";
                $cap->headline = "Wildfire Alert: " . ($data['title'] ?? 'N/A');
                break;
            case 'earthquake':
                $cap->category = ["Geo"];
                $cap->event    = "Earthquake Detection";
                $cap->severity = "Moderate";
                $cap->headline = "Earthquake Detection: Magnitude " . ($data['magnitude'] ?? '?');
                break;
        }

        $cap->urgency     = "Immediate";
        $cap->certainty   = "Observed";
        $cap->description = "Automated message generated by the CoA system for natural hazard monitoring.";
        $cap->areaDesc    = $data['region'] ?? ($data['title'] ?? 'Unspecified Location');

        $extId = $data['external_id'] ?? '0';
        switch ($type) {
            case 'flood':
                $cap->web = "https://www.gdacs.org/report.aspx?eventtype=FL&eventid=" . preg_replace('/[^0-9]/', '', $extId);
                break;
            case 'fire':
                $cap->web = "https://www.gdacs.org/report.aspx?eventtype=WF&eventid=" . preg_replace('/[^0-9]/', '', $extId);
                break;
            case 'earthquake':
                $cap->web = "https://www.emsc-csem.org/Earthquake/earthquake.php?id=" . $extId;
                break;
            default:
                $cap->web = "https://www.gdacs.org/";
        }
    }
}
